### ISSUE TITLE
As a designer create a game ready asset for the character in asteroid

### ISSUE THREAD

**Issue by CCrewe** [UoSGamesGroups/first-semester-l4-5-group-20#13]
Create a game ready, completed asset, for the brain (the main character) in the asteroid mini game, make sure there is a clear front and back so it will be obvious to the player which is which

**Comment by Max-Carter** [comment]
Brain asset completed - uploaded as .psd and .png files under "Assets - Visual" > "Minigame 1 - Asteroids Style"

Time taken - 1 hour
