### ISSUE TITLE
As a designer create the main character sprite sheet

### ISSUE THREAD

**Issue by CCrewe** [UoSGamesGroups/first-semester-l4-5-group-20#14]
Create the sprite sheet for the main character in the hospital portion of the game, six frames of different hand placements and wheel placements should be enough to make the wheel chair look like its actually moving.

**Comment by Max-Carter** [comment]
Added the sprite sheet to "Assets - Visual" > "Main Game Scene" > "MC in
Wheelchair" as both .psd and .png files (as well as a layout picture to
minimise confusion)

Added all the individual frames of the sprite sheet as separate files as
both .psd and .png files under "Assets - Visual" > "Main Game Scene" >
"MC in Wheelchair" > "Individual Frames"

Added a .gif file in the same folder as the individual frames to show
roughly how the animated sprite should look in game.

Time taken - 5 hours 30 minutes
