### ISSUE TITLE
As a designer start sketching and drawing the story boards

### ISSUE THREAD

**Issue by CCrewe** [UoSGamesGroups/first-semester-l4-5-group-20#26]
Start to sketch and draw the first four panels of the story board for the first story board, the dog related one. 

3H

**Comment by Max-Carter** [comment]
All four panels for the "Getting a Dog" storyboard have been sketched and uploaded as both .png and .psd files under 
"Assets - Visual" > "1 - Getting a Dog" > "Uncoloured"

Time taken - 4 hours

**\* While it may not look like 4 hours work, getting the correct outlines I was going for, doing some research and trying to figure out how I wanted the scene to look etc. filled up the time more than I would have liked
