### ISSUE TITLE
As a designer colour in and improve the story boards you already made

### ISSUE THREAD

**Issue by CCrewe** [UoSGamesGroups/first-semester-l4-5-group-20#27]
Work on colouring in and touching up the story boards so that they are usable as game ready assets

3H

**Comment by Max-Carter** [comment]
All 4 storyboard parts for the "Getting a Dog" memory uploaded as .png and .psd files under...
"Assets - Visual" > "Storyboards" > "1 - Getting a Dog" > "Coloured"

Time taken - 4h 30m
