### ISSUE TITLE
As a designer create the fog background for the asteroid game

### ISSUE THREAD

**Issue by CCrewe** [UoSGamesGroups/first-semester-l4-5-group-20#29]
Create four different background of fog for the asteroid game, make them have different levels of opacity. The first one should be basically opaque and you wont be able to see through it, and the fourth one should barely be viable.

2H

**Comment by incogQuw** [comment]
I have created the fog at different stage (doing down in increments of 25% from 100%).

I have moved the task to verify, to wait for it to be checked and moved to completed.

I have added both the psd and png files so that editing can be done if needed.

**Comment by incogQuw** [comment]
2H
