### ISSUE TITLE
As a designer research and create the doctors clipboard

### ISSUE THREAD

**Issue by CCrewe** [UoSGamesGroups/first-semester-l4-5-group-20#30]
Research and create the doctors clipboard for the players room, make sure that there is enough space on the clipboard for us to add text at a later date.

2H

**Comment by incogQuw** [comment]
will change if need be, made the clip board based on the mood board i committed earlier this week, will redo if needed (both psd and png versions uploaded)

**Comment by incogQuw** [comment]
1H 30M
