### ISSUE TITLE
As a programmer, code the player's AoE ability

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#33]
Code the Overload ability the player has - instant kill for all enemies in a decent size radius of the player character on a 45 second cooldown. Please make it so the cooldown and radius are variables that can be adjusted if necessary.

For now, bind this ability to Q

Estimated time - 2 hours

**Comment by CCrewe** [comment]
Completed, but needs some implementation. 1.5h
