### ISSUE TITLE
As a programmer, code the player's shield ability

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#34]
Code the shield ability the player has - absolute protection in a small radius around the player character on a 10 second cooldown. The shield should have 2 seconds of uptime (though this will likely be adjusted). Please make it so the cooldown, uptime and radius are variables that can be adjusted if necessary.

For now, bind this ability to E

Estimated time - 2 hours

**Comment by CCrewe** [comment]
Completed and uploaded.
2h
