### ISSUE TITLE
As a programmer, redesign the player character's movement controls

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#41]
THIS MUST BE COMPLETED BY SUNDAY THE 20TH

Rewrite the code for the player character's movement. Instead of having it so the player character moves forward on command, make it so they move forward constantly. The player must use the W, A, S and D to change direction but will continue to move in that direction (essentially the controls for snake).
W - up
A - left
S - down
D - right

Estimated time - 3 hours

**Comment by E-Ward** [comment]
Task completed and uploaded - Time taken 30 Minutes
