### ISSUE TITLE
As a designer, create a sprite sheet of Interference 2 being destroyed

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#45]
Using one frame from the sprite sheet you made last week for the second interference (which frame you use is up to you), create a 3 frame sprite sheet in photoshop that shows the second interference being destroyed. Move each individual part of the interference outwards (as if it were exploding but don't actually draw any explosion) and play with opacity levels to make it look like the interference is being destroyed.

Upload this sprite sheet as both a .psd and .png file, and upload each individual frame as both .psd and .png files into a separate folder.

Estimated time - 2 hours

**Comment by incogQuw** [comment]
interference sprite sheet completed and uploaded to the repository awaiting verification

2H
