### ISSUE TITLE
As a designer, create the outline for the progress bar

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#46]
A progress bar will be displayed at the top screen (aligned in the centre) which will display the progress the player has made towards unlocking the next part (piece of storyboard) of the memory.
We do not want you to create the progression bar that actually shows the player's progression, just the bar's outline. Try to theme the bar outline (colour and design) on the game's story.
Upload this as both a .psd and .png file.

Estimated time - 1 hour

**Comment by incogQuw** [comment]
created the progress bar and made a png and psd file waiting for verification 

1H
