### ISSUE TITLE
As a programmer, compile the assets into a working prototype

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#47]
MUST BE FINISHED BY SUNDAY 27TH NOVEMBER

1. Compile all the assets we have into a unity file that we can use to playtest in.
2. Make a relevantly named new folder that we can save prototypes and other unity files in

Clean the prototype up, add in all the backgrounds and fog etc.

Estimated time - 3 hours

**Comment by CCrewe** [comment]
Task completed, time taken 3h
