### ISSUE TITLE
As a programmer, code the progression bar

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#48]
MUST BE FINISHED BY SUNDAY 27TH NOVEMBER

Code the progression bar for the game. It should run along the top of the screen aligned in the centre, should decrease significantly whenever the player is hit by the interference or hits the edge of the screen and should increase slightly with every interference that is destroyed.

Estimated time - 2 hours

**Comment by CCrewe** [comment]
Task completed, time taken 2h
