### ISSUE TITLE
As a programmer, code a "round" / "wave" system

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#49]
Code a "round" or "wave" system where enemies spawn over the course of 10 seconds, then 20 seconds where they do not spawn (hopefully giving the player time to kill them). After the 20 seconds is up, this process should repeat.
Both the on-time and off-time should be numbers that can be easily changed as we will likely need to edit these numbers during playtesting.

Estimated time - 2 hours

**Comment by E-Ward** [comment]
Task completed and uploaded - Time taken 2 hours
