### ISSUE TITLE
As a designer, recolour the interference movement sprite sheets

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#52]
Currently both the interference movement sprite sheets have a black, white and grey colour scheme. Because this conflicts with the fog in the background, we need the white and grey portions of the interference to be recoloured as reds. Have a darker red in place of what is currently grey and a 'standard' or lighter red in place of what is currently very light grey / white.
This needs to be done for BOTH of the interference movement sprite sheets.

Save these in the same format as you did with the previous iteration of the sprite sheets but save them in a different folder. We do not want to overwrite them.

Estimated time - 2 hours 30 minutes

**Comment by incogQuw** [comment]
Iv'e recoloured the sprites in both the first and second sprite sheets as requested, I have used 3 different types of red a dark medium and, light red to represent the 3 different colours, I used in the previous black a white sprite sheet.

I have also uploaded both the png and psd version into a sub folder within the visual asset folder named "recoloured interference sheets".

2H 15m
