### ISSUE TITLE
As a designer, create a sprite sheet for the Overload ability

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#54]
When the player presses Q, they will unleash a wide area of effect (AoE) blast that will insta-kill any interference caught in the blast. Create a sprite sheet for this ability being used. It should be comprised mostly of darker blues and some yellows/oranges. We need 6 frames to show the blast's radius rapidly increasing in size and then another 3 frames to show the blast dissipating. For the disspiation frames, keep lowering the opacity and put some blue, yellow or orange dots & streaks in the circle on a low opacity.

This should be saved as both .png and .psd files.

Estimated time - 3 hours

**Comment by joe-sawyer** [comment]
i did this in 30 minutes.
