### ISSUE TITLE
As a designer, rework the Shield's sprite sheet

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#55]
The shield and plasma ball projectile are currently a very similar colour which means they are hard to distinguish between if and when they overlap. We want the shield sprite sheet to be recoloured from blue to purple. We also need the shield to be perfectly circular in every frame.

Save this in the same format as you did the previous shield sprite sheet but do not overwrite the old files.

Estimated time - 2 hours

**Comment by joe-sawyer** [comment]
i have uploaded the file to visuals

time taken 10 minutes.
