### ISSUE TITLE
As a designer, rework the 4 art assets for the fog border lines

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#56]
In its current state, the fog border lines look very scrappy and not too much like actual fog. The colouration is fine but they all need to be smoothed out and rounded more to seem like actual fog.

Overwrite the previous .psd and .png files when saving and uploading.

Estimated time - 1 hour

**Comment by joe-sawyer** [comment]
time taken 15 minutes
