### ISSUE TITLE
As a designer, find a suitable sound effect for when the electrical impulse is fired

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#62]
1. Find a sound effect (copyright free of course) that we can use for when an electrical impulse is fired by the player. Remember the player is going to be firing a lot of these so the sound needs to be very short and fairly quiet.

2. Produce a document in Word (or similar software) that contains a Harvard style reference for the sound file. Please keep all the references for all music and sound effects in the same document.

If you find a long sound file but somewhere in that sound file is a short sound effect you could crop out of it, then use Audacity to crop out that sound effect and delete the rest, but make sure you still reference the whole thing.

Estimated time - 1 hour

**Comment by incogQuw** [comment]
researched music i found suitable for the sound needed for the task

1H
