### ISSUE TITLE
As a designer, find a suitable sound effect for when the overload goes off 

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#64]
1. Find a sound effect (copyright free of course) that we can use for when the player activates the overload ability. This needs to be short and obvious. This one can be quite loud since it is effectively an explosion of sorts.

2. Produce a document in Word (or similar software) that contains a Harvard style reference for the sound file. Please keep all the references for all music and sound effects in the same document.

If you find a long sound file but somewhere in that sound file is a short sound effect you could crop out of it, then use Audacity to crop out that sound effect and delete the rest, but make sure you still reference the whole thing.

Estimated time - 1 hour

**Comment by incogQuw** [comment]
researched music i found suitable for the sound needed for the task

1H
