### ISSUE TITLE
As a designer, find a suitable sound effect for the interference being destroyed

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#65]
1. Find a sound effect (copyright free of course) that we can use for when an interference gets destroyed. Remember the player will probably be hearing this noise very often so make it quite subtle and make it short. I'd suggest a static sounding noise because that's what the intereference effectively are but I'll leave this to your best judgement.

2. Produce a document in Word (or similar software) that contains a Harvard style reference for the sound file. Please keep all the references for all music and sound effects in the same document.

If you find a long sound file but somewhere in that sound file is a short sound effect you could crop out of it, then use Audacity to crop out that sound effect and delete the rest, but make sure you still reference the whole thing.

Estimated time - 1 hour

**Comment by incogQuw** [comment]
researched music i found suitable for the sound needed for the task

1H
