### ISSUE TITLE
As a designer, create a main menu screen

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#66]
THIS MUST BE DONE BY FRIDAY 2ND

Create the main menu screen which will contain...
- The game's title "Interference"
- "Play" button
- "Instructions" button
- "Quit" button

Colour and design are being left up to you, just be sure you're able to explain all your design choices and that they all have a strong relevance to the game. The colour choices should be very similar to or the same as those used in the instruction screen.

If you use any fonts or anything we haven't produced in the group, make a document where you Harvard style reference everything you have used.

Upload this as both .psd and .png files.

Estimated time - 2 hours 30 minutes

**Comment by joe-sawyer** [comment]
time taken 2 hours.
