### ISSUE TITLE
As a programmer, produce the animation for the interference movement sprites

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#68]
Use the following sprite sheets (found under... Assets - Visual\Game Assets\Recoloured interference) to create two animated sprites (one for each sprite sheet) in the unity animation editor. Set both of these to loop.

1. Interference first sprite sheet recoloured.psd
AND
2. interference second sprite sheet recoloured.psd

Estimated time - 2 hours 30 minutes

**Comment by E-Ward** [comment]
45 minutes
