### ISSUE TITLE
As a programmer, produce the animation for the interference destruction sprites

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#69]
Use the following sprite sheets (found under... Assets - Visual\Game Assets\Recoloured interference) to create two animated sprites (one for each sprite sheet) in the unity animation editor. 
These should not loop - just play once and end (since they are being destroyed).

1. explosion interference 1 sprite sheet recoloured.psd
AND
2. interference second sprite sheet explosion Recoloured.psd

Estimated time - 2 hours 30 minutes

**Comment by E-Ward** [comment]
1h
