### ISSUE TITLE
As a designer, crop the music and sound effects to the appropriate lengths

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#70]
THIS MUST BE COMPLETED BY SUNDAY THE 4TH

Go through the sound effect files and using audacity (free software), crop them all to their appropriate lengths. Some of them may fine as they are but others may be 8 seconds long but 6 seconds of that are silence. This silence needs to be cut out.
As for the music, please use audacity to crop it to a point it sound like it can all loop continuously forever. In its current state, the last 15 seconds or so of the song fade out and gets very quiet - this is not good for trying to make something sound continuous. Find a suitable start and end point where it sounds like it can loop forever and then cut out the rest.

Reupload the cropped files into a new folder (as well as any that didn't need any cropping) and please name each file for what the sound will be used for e.g. "background music" or "electrical impulse"

Estimated time - 3 hours

**Comment by incogQuw** [comment]
edited the sounds to make them suit what they are needed for


3H
