### ISSUE TITLE
As a programmer, code the background to change upon 100% completion

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#82]
THIS MUST BE COMPLETED BY SUNDAY THE 4TH

Make it so when the player reaches 100% progress towards the storyboard piece, the background will change to the next piece of the storyboard.

Estimated time - 1 hour

**Comment by CCrewe** [comment]
Task completed, however there is no win condition once the fourth story board has been completed. Time taken 1h
