### ISSUE TITLE
As a programmer, code the menu system

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#83]
THIS MUST BE COMPLETED BY SUNDAY THE 4TH

Code the menu system for the game. The player must be able to go from...
- the main menu to the instruction screen
- the instruction screen to the main menu
- the main menu to the main game
- the main menu to the desktop (quit)

Estimated time - 1 hour

**Comment by CCrewe** [comment]
Task completed, time taken 1 hour
