### ISSUE TITLE
As a designer produce two mood boards based on the research you have found

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#9]
DO NOT ATTEMPT THIS TASK UNTIL YOU HAVE DONE THE RESEARCH (listed as your other task)
1. Use your knowledge from the research you have done to compile two mood boards. You can decide if you want each mood board to convey different things about public hospitals or if they both convey the same things. Remember that mood boards are not just pictures, but also include text relating to what you like or want to include from the images. This makes your mood boards much more specific, useful and efficient as it conveys your research in a more detailed way.
   Please produce these mood boards in photoshop and save them in "Research" > "Joseph" as both .psd and .png file types (total 4 files).

Estimated time - 3 hours

**Comment by CCrewe** [comment]
Task required to be uploaded as a png and psd, so please re create the mood boards on photoshop, and re upload then in both formats.
