### ISSUE TITLE
As a programmer, polish the game until it's in a complete state

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#91]
THIS MUST BE DONE BY SUNDAY

Ensure all the animations are applied to the relevant things, the music and sound effects are all in place and that the game generally runs smoothly. If any bugs are discovered, try as best as possible to get them ironed out. Generally just make sure the game is in the best state possible.

If possible - try to add 4 more spawners in on the corners of the map so the spawns feel less predictable and also to make the player's electrical impulse shots smaller as they are currently quite large

Estimated time - 3 hours

**Comment by CCrewe** [comment]
Time Spent - 5h
