### ISSUE TITLE
As a manager, gather group feedback on the project

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#92]
This should be completed on Tuesday when the group meets up but any members not present should submit their responses via email, social network or text/call.

Gather feedback from all members of the group including yourself, finding out what they've learnt during the process, their general experiences and what are they going to take forward into the next group project. (Refer to Rob's email for more detail as to what to find out)

Compile an easy to understand Word document so that the information can be summed up and put into the final presentation.

Estimated time - 2 hours

**Comment by CCrewe** [comment]
Time taken 1h
