### ISSUE TITLE
As a manager, plan out and suggest how the final powerpoint presentation should look

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#94]
THIS MUST BE DONE BY SUNDAY

Using Rob's email as a guide, suggest how Max can make the final powerpoint look. What slides should be included, what assets should we show on the slides (if any), how much information we need to include etc.
Produce a word document containing this information

Estimated time - 2 hours

**Comment by incogQuw** [comment]
uploaded the work document, and wrote a brief explaniation as to what i think should be on each slide

1.5h
