### ISSUE TITLE
As a designer, record footage of the game for the final presentation

### ISSUE THREAD

**Issue by Max-Carter** [UoSGamesGroups/first-semester-l4-5-group-20#96]
START THIS ON MONDAY AND HAVE IT READY BY TUESDAY NIGHT (team meeting)

Create a video in high quality that lasts approximately 3 minutes that shows all of the game's features.
Ignore the main menu and instructions screen etc, only focus on the actual game. Try to get the sound recorded as well.

This video should at least include... 
- standard gameplay from the very start (the brain and empty screen being filled with the hordes of Interference)
- gameplay of the mid-wave where the player is fighting off large hordes Interference (make sure the player is actually shooting here and not just moving)
- the player using their shield ability (and not taking damage from enemies)
- the player using their overload ability (to destroy several Interference at once)
- the fog levels becoming thinner (beginning to reveal the background)
- the fog being cleared and the panel being shown
- the panels switching over and the fog resetting to be thick again

Edit out any parts you feel are unneccesary. Upload this to a google drive or to youtube as an unlisted video. If this can't be done for some reason, email the team and then bring it along to the team meeting on Tuesday night on a memory stick or external hard drive.

Estimated time - 2 hours

**Comment by E-Ward** [comment]
2 hours
